name: CD

on:
  release:
    types: [created]

defaults:
  run:
    shell: bash

permissions:
  contents: write
  checks: write
  actions: read
  issues: read
  packages: write
  pull-requests: read
  repository-projects: read
  statuses: read

jobs:
  build_linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: make

      - name: Upload Release Asset
        uses: alexellis/upload-assets@0.4.0
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          asset_paths: '["./*.so"]'

  build_osx:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - run: make

      - name: Upload Release Asset
        uses: alexellis/upload-assets@0.4.0
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          asset_paths: '["./*.dylib"]'

  build_windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - run: CC=gcc make

      - name: Upload Release Asset
        uses: alexellis/upload-assets@0.4.0
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          asset_paths: '["./*.dll"]'
