name: CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

defaults:
  run:
    shell: bash

jobs:
  build_linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: make

  build_osx:
     runs-on: macos-latest
     steps:
       - uses: actions/checkout@v3
       - run: make

  build_windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - run: CC=gcc make
